### ISSUE TITLE
Thoughts on adding some default tags to each resource

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/handel#128]
In our organization, we have a tagging policy that dictates adding the following tags to each resource (where possible):
- app
- env
- team
- data-sensitivity

I see that app and env could probably be easily pulled from `handel.yml`.

If at least those two tags could be automatically pulled from the declarations in `handel.yml`, it could cut down on the verbosity of my handel file, yet I imagine not everybody needs those tags.

Thoughts on adding them by default?

**Comment by dsw88** [comment]
I like it, I think we ought to do that. I'm changing this issue type to an enhancement.

**Comment by dsw88** [comment]
I added these default tags, so try removing app and env from the tags in your Handel file. They should still be applied even though you've removed them.
