### ISSUE TITLE
ECS - Support deploying onto shared cluster

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#163]
Some apps are very small and want to be deployed on a shared cluster with other small apps.

This particular feature has some difficulties associated with it. Current options (each with drawbacks) include:

1. Creating shared clusters on-demand, with Handel setting up automated management (scaling, etc.) for the cluster
2. Requiring any shared clusters to be deployed and managed outside Handel, with Handel just deploying into them.
3. Using a non-ECS solution such as Kubernetes on AWS.

**Comment by saholman** [comment]
Is there a disadvantage of doing option 1 for now?  That way a single project with several parts could be managed independently.  Later we could still also implement option 2 with acs managed clusters, etc.

**Comment by dsw88** [comment]
Sorry, I'm not sure which options you're referring to. I changed the description to have numbered options now, can you clarify which one's you're referring to?

**Comment by saholman** [comment]
Sorry.  The options I mentioned above fit with your numbers.  I want to implement option 1 for the LRS project Matthew is working on.

**Comment by dsw88** [comment]
Option 1 is not for the faint of heart, but come talk to me about it and I'll explain some initial thoughts I've had about it.

**Comment by dsw88** [comment]
Oh and I'm not implying you're faint of heart. :) I haven't attempted it yet because there's some tricky bits to figure out.

**Comment by dsw88** [comment]
Now that we have the Fargate service, as well as extensions, I don't think this will be supported in the core of Handel. An extension should be able to be easily written to deploy onto a shared cluster that is managed by other means.
