### ISSUE TITLE
Adding key_name to existing ecs resource doesn't work

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/handel#185]
Added a key_name to an existing ecs resource. Deployment log says that the CF stack was updated successfully, but the EC2 instance wasn't swapped out for a new instance with the key pair associated.

**Comment by dsw88** [comment]
So I don't believe ECS has any built-in logic to rotate your instances when your launch configuration is changed. This means that when you update your key, you currently have to manually roll your instances by terminating them one-by-one. New ones will come up with the correct configuration.

ElasticBeanstalk does this for you, but ECS does not, so we might need to build something into Handel to support this automatically.

**Comment by dsw88** [comment]
Resolved by https://github.com/byu-oit/handel/pull/286
