### ISSUE TITLE
Support for SQS dead letter queues

### ISSUE THREAD

**Issue by saholman** [byu-oit/handel#209]
Setting up a dead letter SQS queue has to be done manually.  Can we give handel the ability to set this up for us?  (http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html).

**Comment by dsw88** [comment]
We sure can do this, I've added it to the roadmap. We're a little swamped with feature requests right now, so it might be a bit before it gets done. Would you be interested/have the time to take a shot at implementing this?

**Comment by saholman** [comment]
Sure, I'll give it a try.

**Comment by dsw88** [comment]
Sweet thanks! Come talk to me and I'll give you an overview of the architecture and how to make contributions to Handel.

**Comment by saholman** [comment]
Resolved by Pull Request https://github.com/byu-oit/handel/pull/222
