### ISSUE TITLE
Handel S3 Static Site upload fails with files > 1MB

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#210]
We are using the node-s3-client library to sync a directory with S3, but it seems to have a bug that will not let it upload files > 1MB from that directory: https://github.com/andrewrk/node-s3-client/issues/184.

We have the following options:

1. Try to fix node-s3-client. There is some concern from recent issues posted on the project about whether this project is maintained currently.
2. Switch to another Node S3 uploader such as https://www.npmjs.com/package/s3-sync. There really aren't many, none of them seem well used, and none of them support a directory sync.
3. Use the AWS CLI for directory syncs, because "aws s3 sync" is fantastic and works flawlessly. This is an external tool that we can't install automatically as a dependency, however, so we'd have to just require that it be pre-installed. We could leave a note in the S3 Static Site docs to that effect and print with a nice error if they don't have it on their system when trying to use it.

I'm leaning towards option 3 myself at the moment, but I'm waiting to see what happens with the issue in node-s3-client.

**Comment by arasmus8** [comment]
In the CodeBuild documentation at http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html it says "The AWS CLI comes preinstalled and preconfigured on all build environments provided by AWS CodeBuild." Wouldn't this mean we could just use `aws s3 sync` no problem?
