### ISSUE TITLE
generate Description for lambda

### ISSUE THREAD

**Issue by bradleyreneer** [byu-oit/handel#219]
![lambda description](https://user-images.githubusercontent.com/7375599/28881197-9548fd96-7764-11e7-90e8-820bc32dbb09.jpg)

Could the handel.yml file allow us to enter descriptions for resources such as a lambda?

**Comment by dsw88** [comment]
Moved this into the roadmap for implementation. It's a really small addition so we can get it done quickly.

**Comment by byujol** [comment]
This features has been merged into the main branch
