### ISSUE TITLE
App and Env tags not automatically created on lambda

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/handel#220]
According to the handel docs:

> Default Tags
> In addition to the ones you specify yourself, Handel will automatically apply the following tags to your AWS resources:
> app - This will contain the value from the name field in your Handel file, which is the name of your overall application.
> env - This will contain the value of the <environment_name> that your service is a part of.

These tags were applied to our CF stack, but not to the underlying lambda that was created.

**Comment by pauldeden** [comment]
Analogous HANDEL* tags were created, but not the OIT standard 'app' and 'env' tags.

**Comment by dsw88** [comment]
These should definitely be getting applied on Lambdas. I'll look at why that's not happening.

**Comment by dsw88** [comment]
@pauldeden and @joshgubler It looks like the code should be applying those default tags to the Lambda. I tried creating a test Lambda service in Handel, and it applied the app and env tags properly to the Lambda. Do you have an example Lambda in an account where they were not applied properly?

**Comment by joshgubler** [comment]
The "autotagger" stack/lambda in the dev account. Unfortunately, the tags are there now because we explicitly added them in our handel.yml. But when we didn't have them in handel.yml, they weren't set on the lambda with default values like we expected. They were added to the stack, but not the lambda.

**Comment by dsw88** [comment]
Can you try removing the added app and env tags from the Handel file in that app to see what happens? I'm a bit confused why they wouldn't be showing up at this point, so it'd be great for me to see a case where that doesn't happen.

**Comment by joshgubler** [comment]
Sure. Let me coordinate with James, as he's the owner of that app.

**Comment by joshgubler** [comment]
Ok. David and I tried to reproduce this issue, but couldn't. Handel is creating default tags as it should.

I believe I misdiagnosed this.

**Comment by joshgubler** [comment]
@pauldeden when you say:

> Analogous HANDEL* tags were created, but not the OIT standard 'app' and 'env' tags.

That's our mistake. Handel doesn't create HANDEL* tags; it creates HANDEL* environment variables. The tags are on a different tab.

**Comment by pauldeden** [comment]
OK, makes sense.
