### ISSUE TITLE
Add custom descriptions for beanstalk, cloudwatchevent, iot, memcached, postgresql and redis

### ISSUE THREAD

**Issue by byujol** [byu-oit/handel#224]
This issue is to track the adding of custom descriptions to handel beanstalk, cloudwatchevent, iot, memcached, postgresql and redis similar to what was done for lamda in issue #219

**Comment by dsw88** [comment]
I think API Gateway might potentially need to be added to the list as well, since it contains a Lambda inside that might need the description added.

**Comment by dsw88** [comment]
Resolved by https://github.com/byu-oit/handel/pull/226
