### ISSUE TITLE
Modify naming for environment variables and parameters store parameters

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel#270]
For env vars remove the first 3 parts of the prefix.  They are not needed since they are only shown to one app at a time.

For parameter store parameters inject an env var called something like HANDEL_PS_PREFIX that contains the parameter store prefix so developers don't have to remember how to construct the prefix.

This simplification should remove the need to write SDKs like https://www.npmjs.com/package/handel-utils for each language that we use.

We need to be careful about backwards compatibility.

**Comment by ThatJoeMoore** [comment]
FYI, I'm developing this in ThatJoeMoore/better-env-vars .

**Comment by GaryGSC** [comment]
Concerning the `HANDEL_PARAMETER_STORE_PREFIX` environment variable, if services are given IAM access to SSM parameters starting with `<application_name>.<environment_name>`, why does handel provide a value of `<application_name>.<environment_name>.<service_name>` for this variable?

As it stands, I would have to go back to manually constructing the SSM prefix to access any variables that aren't namespaced by service name, which seems contrary to the intent of this addition.

**Comment by dsw88** [comment]
Oops, apologies about that! It was intended to reflect the true prefix, which is <appName>.<envName>. Everything else after that is user-specified. I will put out a fix for that.

**Comment by dsw88** [comment]
I fixed the parameter store prefix in https://github.com/byu-oit/handel/pull/275. Try again and it should work this time.
