### ISSUE TITLE
SES - Add permission to send email

### ISSUE THREAD

**Issue by brettbeatty** [byu-oit/handel#285]
I have a Lambda, deployed through Handel, that needs to send email through SES. SES does not appear to have any CloudFormation resources of its own, so I just need the Lambda to have the `ses:SendEmail` permission (and hidden permissions behind that, if any) for the `arn:aws:ses:<region>:<account>:identity/<email_address>` resource (again, I'm not finding the resource type in the CloudFormation docs--I just have this set up through the console).

**Comment by dsw88** [comment]
We'll want to make this a service type of its own so that not just Lambda but any other compute service can consume SES to send emails. I've added this to the backlog.

**Comment by brettbeatty** [comment]
I am attempting to figure this out in the `ses` branch and welcome any input/help.

**Comment by dsw88** [comment]
This has been implemented: http://handel.readthedocs.io/en/latest/supported-services/ses.html
