### ISSUE TITLE
Modify how we create/update CF stacks to use S3

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#291]
The template size limit for S3 objects is about 11x bigger, so this will allow for bigger stacks created using Handel. For example, this API Gateway service breaks because it defines a lot of Lambdas: https://github.com/crslade/HomeAPI/blob/master/handel.yml

**Comment by IDT-kcrook** [comment]
👍 Developers are needing to split up their swagger files into separate API gateways because of hitting limits with CloudFormation stacks. This enhancement would help immensely!

**Comment by dsw88** [comment]
@IDT-kcrook This has been implemented, so people should be able to get larger stack sizes on their templates. I think the new limit is something like 4.6MB, so there is definitely still a limit that we will not be able to increase any further.

For the case of API Gateway, I still highly recommend avoiding having a single Lambda function for each route/HTTP method combination. That results in a ton of Lambdas for a single service, and provides very little tangible benefits. A better approach is to share a single Lambda for all the HTTP methods in a given route.
