### ISSUE TITLE
Initial run in an account gave an error.

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#308]
On the first run in a new account (for Handel), we got this error: "Your previous request to create the named bucket succeeded and you already own it."

The second run succeeded.

**Comment by zbrogz** [comment]
Were you able to reproduce this on your aws account?

**Comment by dsw88** [comment]
I was unable to reproduce this when running Handel in a new AWS account. Closing for now until we can get someone to reproduce this.
