### ISSUE TITLE
ECS - Container names with dashes break deployment

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#320]
An app that had an ECS container name with dashes in it failed to deploy with this message:
```
Error during environment deploy: Template format error: Resource name AlbListenerRulesome-container-name is non alphanumeric.
```
We are using the container name when building the CloudFormation resource, which is why this breaks when you have dashes.

I think we should allow dashes in the container name, so we need to come up with a different way of constructing those resource names.

**Comment by ThatJoeMoore** [comment]
I've got a PR almost ready for this. We've got a handlebars helper that can solve this problem.

**Comment by dsw88** [comment]
Awesome thanks!
