### ISSUE TITLE
Allow additional parameter store values to be specified for access

### ISSUE THREAD

**Issue by bwinterton** [byu-oit/handel#324]
Currently Handel auto provisions the IAM rights to allow for access to a predetermined set of parameter store values (those containing the right prefix). However, we have several cases where parameters are shared between multiple pieces of code and infrastructure. It would be nice to allow the user to specify a list of explicit parameter store values (or prefixes) to allow reading from.

**Comment by dsw88** [comment]
Handel now supports global parameters: https://handel.readthedocs.io/en/latest/handel-basics/accessing-secrets.html#global-parameters. These are global to the account, meaning any Handel app in the account can read them.

I'm not sure how to safely do anything else in between. Handel can't know for sure whether you're authorized to access a list of parameters that you specify. I recommend using global parameters if they can be publicly visible to the whole account. If they can only be visible to a few different applications, I recommend copying the parameters to the various namespaces.
