### ISSUE TITLE
Fargate: ALB Listener

### ISSUE THREAD

**Issue by ndpete** [byu-oit/handel#337]
ALB Listener shouldn't use the container name directly.

**Comment by dsw88** [comment]
@ndpete I've forgotten the details about this issue, can you provide some more information about this issue?

**Comment by ndpete** [comment]
haha I can't remember exactly either. I just remember it came up while we were working on getting the support out so we created the issue to not forget it later.

**Comment by dsw88** [comment]
I can't remember either, so I'm going to close this issue. I'm sure if there still is an issue related to the ALB listener that hasn't been fixed yet it will come up again.
