### ISSUE TITLE
DynamoDB - global index partition key type set to S instead of N

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/handel#346]
When you create a global index with a partition key and set that partition key type as a Number, the CF template handel generates defines the field as an S instead of an N.

**Comment by yoshutch** [comment]
https://github.com/byu-oit/handel/blob/efd20f25f364d25812770ada877c3ef9555caa3b/src/services/dynamodb/index.js#L132
This looks to be the issue, I'm not sure, but it looks like on this line it's not looking at the global index's type

**Comment by dsw88** [comment]
I believe you are correct about the issue, I fixed it in commit https://github.com/byu-oit/handel/commit/24f3a32e89a39c35d298bd295999a614349e17ee. Try a deploy on a new table to see if things work.

**Comment by dsw88** [comment]
The fix worked, I'm closing this issue.
