### ISSUE TITLE
Add extensible Handelfile validation

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/handel#370]
This is a top-level issue to discuss one of the ideas in #332, namely, adding a way for an organization to enforce extra pre-deployment validation rules, such as making sure that all tag values are correct.

My initial idea was to be able to specify the name of a Lambda function in the account config file, then have Handel pass the parsed Handel environment to it and get a response back with any errors.

I'm no longer certain that this is the best way to tackle this problem. I wonder if, instead, this should be part of implementing our Plugin/Extension system (#302). That may make things a lot simpler - for example, `handel check` would be able to run locally, without being logged into AWS or having to mess with permissions on the checker lambda. It also adds debuggability and a built-in update distribution mechanism (npm).

It does, however, add some wrinkles. For example, how do you mandate that everyone in an organization have your validator plugin installed? What's to prevent some unknowing developer from getting frustrated with the rules in it and uninstalling it, not realizing that they're violating policy?

One idea might be to have a list of required plugins in the account config file. Then, we may be able to get the benefits of central configuration and enforcement without it actually being truly centralized and, therefore, being a single point of failure.

**Comment by ThatJoeMoore** [comment]
Yeah...the more we consider this, the more it feels like enforcement of complex rules is beyond the scope of Handel. There's already a tool for that - AWS Config. We've provided all of the tools to get us pointed in a direction where Config could be useful - given a resource, as long as things are using the latest version of Handel and Handel-Codepipeline, you can have a Config rule that flags non-compliant resources and track that back to a committer.

Handel should do one thing, do it well, and then move on. It's a deployment tool, not a policy enforcer. AWS already has a policy enforcer, and we should use it.

**Comment by dsw88** [comment]
I concur. We've now got some great facilities to help enable organizational tagging. I do also feel that things like enforcement of valid team group names should be an AWS Config rule that's part of our account config project.
