### ISSUE TITLE
Set environment variable for AWS region

### ISSUE THREAD

**Issue by mhailstone** [byu-oit/handel#412]
I was deploying a Fargate application and ran into the problem that the AWS region was defaulted to 'us-west-2'. It would be convenient to have a Handel environment variable that provides the AWS region that you are in. I know that you can make the following request to discover the current AWS region in a deployed process:
`curl --silent http://169.254.169.254/latest/meta-data/hostname | cut -d\. -f2`

But, it would still be very nice for the application to be able to reference the AWS region as a Handel environment variable.

Something like: HANDEL_AWS_REGION or HANDEL_CURRENT_AWS_REGION

**Comment by dsw88** [comment]
You can now use the HANDEL_REGION_NAME variable to get this information: https://handel.readthedocs.io/en/latest/handel-basics/consuming-service-dependencies.html#common-injected-environment-variables
