### ISSUE TITLE
Postgres - Add support for version 10.x

### ISSUE THREAD

**Issue by dsw88** [byu-oit/handel#437]
We have to know which parameter group family to use, so we'll need to update this code before 10.x can be used: https://github.com/byu-oit/handel/blob/master/handel/src/services/postgresql/index.ts#L36

**Comment by joshgubler** [comment]
According to [this page](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html):

```
$ aws rds describe-db-engine-versions --query "DBEngineVersions[].DBParameterGroupFamily"
...
    "postgres10",
...
```

Do we want to make 10 the new default? Or leave 9.6 as the default?

**Comment by dsw88** [comment]
The postgres_version parameter is required, so we don't have a default set for that. It used to have a default, but I decided it isn't safe to have a moving major version default, so we now make people explicitly specify which version they want to use.

The code to choose parameter group types probably needs to be updated to throw an error if anything other than expected values is given, rather than having a default parameter group name as it's currently implemented.

**Comment by dsw88** [comment]
Implemented in https://github.com/byu-oit/handel/commit/5f89ea94fcf104b35780833910ecf7ceb1aa1950
