### ISSUE TITLE
[Discussion] Change Parameter Store Parameters naming convention

### ISSUE THREAD

**Issue by ndpete** [byu-oit/handel#441]
I recently discovered that Parameter Store is tooled and designed to utilize paths ([Blog Post](https://aws.amazon.com/blogs/mt/organize-parameters-by-hierarchy-tags-or-amazon-cloudwatch-events-with-amazon-ec2-systems-manager-parameter-store/)). Currently we generate parameters store parameters with prefixes delineated with `.` ie `my-lambda-app.dev.somesecret`

I wonder your thoughts on changing to use paths for naming. ie `/my-lambda-app/dev/somesecret` which would allow us to utilize the various parameter path apis/features.

**Comment by dsw88** [comment]
Implemented in https://github.com/byu-oit/handel/pull/584.
