### ISSUE TITLE
Handel rejects fargate container with "-"

### ISSUE THREAD

**Issue by romrell4** [byu-oit/handel#446]
```
[31merror[39m:   Error during environment deploy: Template format error: Resource name AlbListenerRuleparking-rest is non alphanumeric.
```

Hyphens not allowed. Should handel clean this for us?

**Comment by dsw88** [comment]
This is related to https://github.com/byu-oit/handel/issues/320. I wasn't aware of this naming limit until I ran into it a little while ago. That issue is still open, nothing has been done on it yet. I'll push it up the priority list a bit.
