### ISSUE TITLE
Add HTTPS redirect support to ALB

### ISSUE THREAD

**Issue by ndpete** [byu-oit/handel#496]
Add HTTPS redirect support to ALB for services that utilize an ALB ie (ECS, Fargate, etc)
https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/

**Comment by dsw88** [comment]
This isn't yet supported in Cloudformation or Beanstalk. We can add it as soon as they support it. AWS told me that they have feature requests open for it, but can't guarantee a release date.

**Comment by dsw88** [comment]
This is still not supported by CloudFormation, we might want to add this to Handel anyway using other means, then switch over to the CloudFormation once it's supported.

Here's an example of someone using a custom CF resource to provide the redirect support: https://github.com/jheller/alb-rule
