### ISSUE TITLE
SQS Schema is incorrect

### ISSUE THREAD

**Issue by ndpete** [byu-oit/handel#526]
https://github.com/byu-oit/handel/blob/07d2a6b35d7476623656013fcd3cc0ed5391aa99/handel/src/services/sqs/params-schema.json#L11-L15

This shows a property of query_type instead of queue_type as shown in the docs: https://handel.readthedocs.io/en/latest/supported-services/sqs.html

**Comment by dsw88** [comment]
Resolved in https://github.com/byu-oit/handel/commit/a0c251b39364db577f9cb628e5bedf5251659818
