### ISSUE TITLE
RDS writing paramters to SSM using deprecated notation

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/handel#600]
This should be updated to use `/` notation:

https://handel.readthedocs.io/en/latest/supported-services/postgresql.html

![image](https://user-images.githubusercontent.com/9257908/53593064-ef530d80-3b54-11e9-8d98-11f005c3a0c8.png)

**Comment by ndpete** [comment]
Yeah all of the services that write parameters need to be updated to path notation. Goes back to the original discussion of how to deprecate and retire paths. So many deployments are using the dot notation now.
